import "./globals.css";
import "../../assets/css/custom.css";
import type { Metadata } from "next";

import Layout from "@/components/layouts";
import { headers } from "next/headers";
import { Suspense } from "react";
import ReactQueryProvider from "@/providers/ReactQueryProvider";

import NextProgress from "@/components/next-progress";
import Head from "next/head";
import ReduxProvider from "@/redux/store-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const headersList = await headers();
  return (
    <html lang="en">
      <Head>
        <meta name="robots" content="noindex, nofollow" />
      </Head>
      <body>
        <Suspense >
          <ReactQueryProvider>
            <NextProgress />
            <ReduxProvider subdomain={headersList.get('host')}>
              <Layout hostName={headersList.get('host')}>
                {children}
              </Layout>
            </ReduxProvider>
          </ReactQueryProvider>
        </Suspense>
      </body>
    </html>
  );
}
